services:
  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: ../Dockerfile.backend.dev
    ports:
      - 4000:4000
  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: ../Dockerfile.frontend.dev
    environment:
      - BACKEND_URI=http://backend:4000
    ports:
      - 3000:3000
    depends_on:
      - backend
