FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY assets ./assets
COPY public ./public
COPY src ./src
COPY index.html ./
COPY vite.config.ts ./

CMD ["npm", "run", "dev"]